config/routes.rb
Rails.application.routes.draw do
 root 'welcomes#index'
 resources :welcomes
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index

  end
  
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index
    @abouts = About.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  def index
    @podcasts = Podcast.all
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
    @welcomes = Welcome.all
  end

  def new
    @welcomes = Welcome.new
  end

  def create
    Welcome.create(welcome_params)
    redirect_to root_path
  end

  private

  def welcome_params
    params.require(:welcome).permit(:title, :message)
  end


end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heroic Nonsense</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to 'Brought to you by Nathan D Ward, and Rovin J Onas', root_path, class: 'navbar-brand' %>
<br/>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
                <%= link_to 'New Comment', new_welcome_path, class: 'nav-link' %>
                <i class="fa fa-plus-circle"></i>
              </li>
  
            </ul>
            
          </div>
        </nav>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Such Heroic Nonsense</h1>

app/views/welcomes/index.html.erb
<br />
<br />

<h1 class="pagetitle">Such Heroic Nonsense</h1>
<hr />
<h2 class="infotitle">Coming soon...</h2>
<br />
<br />


<% @welcomes.each do |welcome| %>
  <div class="booyah-box col-sm-6 offset-3">
    <h5><%= welcome.title %></h5><br />
    <p><%= welcome.message %></p><br />
    
  </div>

  <hr />
<% end %>

app/views/welcomes/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Enter your welcome page comment details</h1>
<%= simple_form_for @welcomes do |f| %>
    <%= f.input :title %>
    <%= f.input :message %>
    <br />
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>